name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run_python_script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x # Replace with your desired Python version
      
    - name: Install dependencies
      run: |
        pip install GitPython
      shell: bash
      
    - name: Run Python Script
      run: |
        python - >-
          import subprocess

          result = subprocess.run(['git', 'log', '--pretty=format:%H,%an,%ad,%s'], stdout=subprocess.PIPE, text=True)
          print(result.stdout)
